name: Build and Push Docker image

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/jrs:latest

  sync-to-aliyun:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to Alibaba Cloud Registry
        run: |
          echo "${{ secrets.ALIYUN_PASSWORD }}" | docker login --username=${{ secrets.ALIYUN_USERNAME }} --password-stdin crpi-e38l2v1is4373ixk.cn-shanghai.personal.cr.aliyuncs.com

      - name: Pull image from DockerHub
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/jrs:latest

      - name: Tag and push image to Alibaba Cloud
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/jrs:latest crpi-e38l2v1is4373ixk.cn-shanghai.personal.cr.aliyuncs.com/${{ secrets.ALIYUN_USERNAME }}/jrs:latest
          docker push crpi-e38l2v1is4373ixk.cn-shanghai.personal.cr.aliyuncs.com/${{ secrets.ALIYUN_USERNAME }}/jrs:latest
